### ISSUE TITLE
Empty output files on Windows

### ISSUE THREAD

**Issue by jhawkinsatgood** [alanshaw/markdown-pdf#40]
Hi, I just updated to the latest markdown-pdf on my Windows and Mac machines. The Mac is OK, although still only produces images because of a phantomjs limitation, I guess. The Windows now generates zero-length output.

It seems to process for the expected amount of time, but the output is empty.

Any ideas of things to try?

Cheers, Jim

**Comment by alanshaw** [comment]
Hi @jhawkinsatgood, thanks for reporting. I don't know what that could be off the top of my head. I can't remember ever using it on windows - does it definitely work with a previous version?

**Comment by jhawkinsatgood** [comment]
Yah definitely, in fact it used to work better because it generated text PDFs, not just an image per page.

**Comment by alanshaw** [comment]
Ok, I'm looking at this in windows vista and I get a PDF but the styles haven't been loaded. It takes a while to generate, but it gets there in the end.

So I have a different bug to fix...

What windows are you rocking?

**Comment by alanshaw** [comment]
I've tried this on windows 8 as well and I get output so I can't replicate this. I have published a fix for the resource loading problem as markdown-pdf@4.0.1

**Comment by jhawkinsatgood** [comment]
I am running Windows 7 Enterprise. I just tried a test with a very simple file and still get nothing.
Would there be a way to test my phantomjs installation? Meantime, I'm going to uninstall and reinstall all my npm gubbins.

**Comment by jhawkinsatgood** [comment]
Oh well, now I look a bit silly because uninstalling and reinstalling seems to have fixed it. Very sorry about that. As you were and keep up the good work. Cheers, Jim
